# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hdeniz <Discord:@teomandeniz>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/22 12:48:13 by hdeniz            #+#    #+#              #
#    Updated: 2024/07/22 12:51:01 by hdeniz           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.9'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
        - CERTS_KEY
        - CERTS_CRT
    expose:
      - 443
    networks:
      - connection
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
      - static_volume:/usr/share/nginx/html
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - static
  wordpress:
    container_name: wordpress
    expose:
      - 9000
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    networks:
      - connection
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    expose:
      - 3306
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    networks:
      - connection
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always
################################ [v] BONUS [v] #################################
  redis:
    container_name: redis
    build:
      context: ./requirements/BONUS/redis
    networks:
      - connection
    restart: always
    expose:
      - 6379
    depends_on:
      - nginx
  ftp:
    container_name: ftp
    build:
      context: ./requirements/BONUS/ftp-server
      args:
        - FTP_USER
        - FTP_PASSWORD
    networks:
      - connection
    volumes:
      - wordpress_volume:/home/$FTP_USER/ftp
    ports:
      - "20:20"
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
    depends_on:
      - nginx
  static:
    container_name: static
    build:
      context: ./requirements/BONUS/static-website
    networks:
      - connection
    volumes:
      - static_volume:/usr/src/app
    restart: always
    expose:
      - 3000
  adminer:
    container_name: adminer
    build:
      context: ./requirements/BONUS/adminer
    networks:
      - connection
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    expose:
      - 9000
    depends_on:
      - wordpress
  cadvisor:
    init: true
    container_name: cadvisor
    build:
      context: ./requirements/BONUS/cadvisor
    networks:
      - connection
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    depends_on:
      - nginx
################################ [^] BONUS [^] #################################
volumes:
  mariadb_volume:
    name: mariadb
    external: true
  wordpress_volume:
    name: wordpress
    external: true
  static_volume:
    name: static
    external: true
networks:
  connection:
    name: connection
    driver: bridge